# Generated by Django 4.2.7 on 2023-11-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Mixed', 'Mixed')], max_length=200, null=True),
        ),
    ]
