# Generated by Django 4.2.7 on 2023-11-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='customer',
            name='images/logo example.png',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
