# Generated by Django 4.2.7 on 2023-11-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customer_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='images/logo example.png',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/logo example.png', null=True, upload_to=''),
        ),
    ]
