# Generated by Django 4.2.7 on 2023-11-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customer_email_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile icon.png', null=True, upload_to='static/images/customer_profile_pic'),
        ),
    ]
